spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

    contentnegotiation:
      favor-parameter: true # 开启请求参数内容协商模式，仅支持 format=json 或 format=xml 两种参数

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB